### PR TITLE
Do not call .verison() when CARGO_PKG_VERSION is not set

### LINKED ISSUE #243: Accept rustflag equivalent to no_version
Structopt currently looks at the environment variable $CARGO_PKG_VERSION to determine a version for the command line app. In non-Cargo environments this environment variable doesn't make sense and we would prefer to use no_version by default everywhere.

I would recommend for structopt-derive to accept a rustflag cfg that disables the check for CARGO_PKG_VERSION and assumes no_version by default.

```shell
RUSTFLAGS='--cfg structopt_no_version' cargo build ...
```

If a `version = "..."` attribute is present, that should take precedence over structopt_no_version.

Implementation-wise this would look like `#[cfg(structopt_no_version)]` and `#[cfg(not(structopt_no_version))]` codepaths in structopt-derive.

cc @bolinfest

### PR DESCRIPTION
**Pull request by CreepySkeleton**
It looks like we can arguing on #243 just forever. 

Docs are upcoming

fixes #243

### CODE REVIEW

**Comment by TeXitoi** [comment]
Waiting for the doc.

**Comment by CreepySkeleton** [comment]
Written and redacted by me the magnificent! I believe docs are in sync with current implementation, more or less. Could use some future proofreading though.

**Comment by dtolnay** [comment]
Thanks! Would it be possible to get an 0.3.1 release with this change?

**Comment by TeXitoi** [comment]
wait a few seconds, I'm doing it ;-)

**Comment by TeXitoi** [comment]
v0.3.1 published

**Pull request merged**
