### PR TITLE
Fix use of deprecated string functions

### PR DESCRIPTION
**Pull request by owenthewizard**

### CODE REVIEW

**Comment by TeXitoi** [comment]
For that, the minimum rust version must be changed.

**Comment by owenthewizard** [comment]
Travis Rust is too old?

**Comment by owenthewizard** [comment]
Sorry, didn't even see your comment. When/if do you anticipate a minimum version bump?

**Comment by TeXitoi** [comment]
As of the structopt policy, we can update to the supported clap version when we want. See the readme.

**Comment by owenthewizard** [comment]
I don't think this "improves the library experience" per se, so perhaps merging this can wait until something more worthwhile bumps the version.

**Comment by TeXitoi** [comment]
I've cherry-picked the interesting commit

**Pull request closed without merging**
