### PR TITLE
Rust 2018

### PR DESCRIPTION
**Pull request by hrls**

### CODE REVIEW

**Comment by TeXitoi** [comment]
Thanks.

Before reviewing this, #198 must be merged. So sorry if I take a bit of time before comming back to this PR.

**Comment by TeXitoi** [comment]
#198 is merged, please update this PR.

Thanks again for your contribution.

**Comment by 0ndorio** [comment]
@hrls Thanks for the changes :)  I think you missed to update the `structopt-derive` subcrate and the test cases inside the `test/ui` directory.

**Comment by TeXitoi** [comment]
I've taken your commit and finished the migration. Your contribution appear in the history.

Thanks again!

**Pull request closed without merging**
