### PR TITLE
Fix wrong span

### LINKED ISSUE #424: error[E0425]: cannot find value `app` in this scope
I have the following code:
```rust
use structopt::StructOpt;

macro_rules! Command {
  ( $name:ident, [
    #[$meta:meta] $var:ident($inner:ty)
  ] ) => {
    #[derive(Debug, PartialEq, structopt::StructOpt)]
    enum $name {
      #[$meta] $var($inner),
    }
  };
}

Command! {GitCmd, [
  #[structopt(external_subcommand)]
  Ext(Vec<String>)
]}

// Works:
//#[derive(Debug, PartialEq, StructOpt)]
//enum GitCmd {
//  #[structopt(external_subcommand)]
//  Ext(Vec<String>),
//}

fn main() {
  assert_eq!(
    GitCmd::from_iter(&["test", "git", "status"]),
    GitCmd::Ext(vec!["git".to_string(), "status".to_string()]),
  );
}
```

And it fails to compile (0.3.16, default features):
```
error[E0425]: cannot find value `app` in this scope
 --> src/main.rs:7:32
  |
7 |     #[derive(Debug, PartialEq, structopt::StructOpt)]
  |                                ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `foo`.

To learn more, run the command again with --verbose.
```

I checked the [expanded output](https://gist.github.com/d-e-s-o/4653b9ba305654bd6733573913c011a3) and everything seems perfectly fine.

So then I came up with the following patch to `structopt-derive`:
```diff
--- lib.rs
+++ lib.rs
@@ -481,7 +481,7 @@ fn gen_augment_clap_enum(
         let kind = attrs.kind();
         match &*kind {
             Kind::ExternalSubcommand => {
-                quote_spanned! { attrs.kind().span()=>
+                quote! {
                     let app = app.setting(
                         ::structopt::clap::AppSettings::AllowExternalSubcommands
                     );
```

And now everything works. I am not really sure what to make of that. I checked the `quote_spanned` macro but nothing stood out. Any ideas?

### PR DESCRIPTION
**Pull request by CreepySkeleton**
Closes #424

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Once that change is in, would it be possible to cut a new release? I need the fix for work I am currently doing.

**Review by TeXitoi — APPROVED** [review]

**Comment by TeXitoi** [comment]
@d-e-s-o won't it only affect error messages?

**Comment by TeXitoi** [comment]
self reply: OK read the corresponding issue, it's not.

**Comment by CreepySkeleton** [comment]
@d-e-s-o `0.3.17` Behold: is about to be released!

**Comment by d-e-s-o** [comment]
Thank you @CreepySkeleton & @TeXitoi for the fast turnaround on this one! Greatly appreciate it!

**Pull request merged**
