### PR TITLE
Add table of contents in documentation

### PR DESCRIPTION
**Pull request by CreepySkeleton**
`structopt`'s documentation has grown much, now it's not easy to navigate. Table of contents would help a lot.

### CODE REVIEW

**Comment by CreepySkeleton** [comment]
@TeXitoi This travis failure is due to some cache problems, it has nothing to do with the PR. I suggest you to clear the travis cache

**Comment by TeXitoi** [comment]
Thanks.

**Comment by CreepySkeleton** [comment]
@TeXitoi Did you clear only the nightly cache? Just compare build times: ~5 minutes for nightly and ~10+ minutes for beta and stable. Looking at the timestamps, I see cache unloading/acking takes up to 9 minutes which is more than 70% of the build time. I'd say the cache does more harm than good for a such small crate as structopt, I suggest to clean in weekly (there must be a way to automate this task) or even disable at al.

**Comment by TeXitoi** [comment]
I deleted all the cache of the project. But I only relaunched the nightly build.

**Comment by TeXitoi** [comment]
I can't find any option to clear the cache regularly. I'm removing it.

**Comment by TeXitoi** [comment]
removed in 6be2b48

**Pull request merged**
