### PR TITLE
[Casing] Change default from verbatim to kebab.

### PR DESCRIPTION
**Pull request by 0ndorio**
.. fixes TeXitoi/structopt#202

I hope I discovered all related comments and text snippets.

### CODE REVIEW

**Comment by TeXitoi** [comment]
Thanks. Will try to review today.

Please update the changelog.

**Comment by 0ndorio** [comment]
> Thanks. Will try to review today.
> 
> Please update the changelog.

Done. Listed it inside the `Breaking Changes` category.

**Comment by TeXitoi** [comment]
Sorry to not been explicit enough: can you add a note in the changelog explaining how to have the same behavior as before, for ease of upgrading? Thanks.

**Comment by 0ndorio** [comment]
> Please improve the documentation at the begining of lib.rs, explaining that, by default, `long`, `short` `name` and commands without explicit name will be renamed using kebab-case if rename-all is not specified.
> 
> Else, everything looks good, thanks!

Updated the change log  and added an additional paragraph to describe the behavior (I hope it's in the right place).

**Comment by TeXitoi** [comment]
Thanks!

**Pull request merged**
