### PR TITLE
Add an example of a negative flag (i.e. --no-verbose)

### PR DESCRIPTION
**Pull request by TeXitoi**
Question from https://github.com/TeXitoi/structopt/issues/280

### CODE REVIEW

**Comment by CreepySkeleton** [comment]
Frankly, I don't think that we should attempt to document usage of `clap::Arg` methods on main docs.rs page. It's just there are too many `clap::Arg` methods and a lot of clever tricks to do. 

I would like to propose a **separate** "`structopt` cookbook" containing a set of handy tips and tricks, say, `Tips and Tricks.md` file in github repo.

**Comment by TeXitoi** [comment]
until now, I've collected in the example "classical" questions about use cases, mainly from questions as this one. People seems to look at it, and if not, I just point to the example if such a question arrise.

Then, if you want to write a `Tips ans tricks.md`, feel free to propose such a PR, I think it would be a great addition.

**Comment by TeXitoi** [comment]
And examples doesn't go in docs.rs afaik, and having these examples compiling is also of interest.

**Comment by CreepySkeleton** [comment]
Oh, you mean `examples` folder?

**Comment by TeXitoi** [comment]
Yep, this is a new file in the example folder

**Comment by TeXitoi** [comment]
I don't get the Ctrl+F thing.

OK for a README.md in the examples folder, but i think that's not related to this PR.

**Comment by CreepySkeleton** [comment]
> 
> 
> I don't get the Ctrl+F thing.

I mean, there's no easy way to perform a *search*. Examples are just a bunch of `*.rs` files and there's no description; if I'd needed something specific I would have to pick a file based on its name only, most likely, not just one (I'm speaking from experience).
 
> OK for a README.md in the examples folder, but i think that's not related to this PR.

Yeah, this is meant to address the lack of description. For example:

```markdown
# Collection of useful tips and tricks

### Parse "true" or "false" literals as `bool` flag

[Short description, detailed description goes into the file]
Parse `"true"` or `"false"` literals as CLI flag and turn it into a `bool` field.

[Full example](link to rs file)  
[Origin](link to issue/PR/comment)

[Short snippet, nothing fancy, core idea only, detailed description should be put into the corresponding file]
```rust
type Flag = bool;

#[derive(StructOpt)]
struct Opt {
    flag: Flag
}

... other entries, sorted alphabetically
```

This way we can direct the browser to `examples` folder and get a quick overview about the stuff contained. 
Also, if this way I would be able to hit `Ctrl+F`, search for `"true"` and instantly find exactly what I want.

**Comment by TeXitoi** [comment]
OK, but I'd prefer no code in the README, that's a pain to maintain.

**Comment by CreepySkeleton** [comment]
> 
> 
> OK, but I'd prefer no code in the README, that's a pain to maintain.

I thought these examples never change spontaneously, only on major releases.

**Comment by TeXitoi** [comment]
That's easy to forget to change the README at a new breaking change release, or when you update the code of the example, or when you do a bad copy/paste that doesn't compile. As the example must be short, reading the example should be accessible.

**Comment by CreepySkeleton** [comment]
Hey, @TeXitoi , is this blocked on something so you can't merge it?

**Comment by TeXitoi** [comment]
I was waiting for you to merge or approve the merge request. We need to define a workflow ;-)

What about "the author of the pull request can merge himself after an approve, or a "too big" timespan without feedbacks"?

**Comment by CreepySkeleton** [comment]
Sure, I think 4 days would be a good "no reply" time span

**Comment by CreepySkeleton** [comment]
Also, I think it would be sencible to allow merges without an approval as long as it's small and it doesn't change anything in `src/structopt_derive` folder (examples, tests, docs...)

**Comment by TeXitoi** [comment]
OK, deal! ;-)

**Comment by TeXitoi** [comment]
Did you received my crates.io invitation?

**Comment by CreepySkeleton** [comment]
Also, where is the "approve" button here? I couldn't find it :)

**Comment by TeXitoi** [comment]
When looking at the diff, you have an approve button

**Comment by TeXitoi** [comment]
Review changes

**Comment by CreepySkeleton** [comment]
Ooops, I totally missed it. I didn't receive an email so I didn't know about it, sorry. 

> 
> 
> Review changes

Are you asking me to review some changes or keep explaining the location of "approve" button? I found it :)

**Comment by TeXitoi** [comment]
keep explaining the location of "approve"

**Comment by TeXitoi** [comment]
For publishing, I always publish structopt-derive and structopt at the same time with the same version, even if most of the time structopt doesn't need an update. That's clearer if the version numbers are the same.

So, the publish workflow is, for now:
 - edit CHANGELOG.md, Cargo.toml and structopt-devive/Cargo.toml to update the versions
 - commit locally on master
 - cd structopt-derive && cargo publish
 - cd .. && cargo publish
 - git tag v0.3.5
 - git push origin master && git push origin --tags
 - notify the persons on the merge request if I'm not lazy

We can change that if you have a better idea.

**Comment by CreepySkeleton** [comment]
That's a good workflow, but I would advice to do `tag && push` before publish so we could have a CI run on the same comment as `cargo publish`.

Also, maybe I'll even find some time and write a script to automatize stuff, mundane manual actions tend to have some really unpredictable mistakes snaked in :) Hail machines, hail SkyNet!

**Comment by CreepySkeleton** [comment]
And, just so you know, if you need to get in touch with me for some reason that is unrelated to github (like the crates.io invite) you should send me an email, I typically check it at least once a day. the same if you're need a reply from me as soon as possible.

**Comment by CreepySkeleton** [comment]
Do you still need `example-negative-branch`?

**Comment by TeXitoi** [comment]
good catch, removed

**Comment by TeXitoi** [comment]
OK, the one listed in your profile?

**Comment by CreepySkeleton** [comment]
Yep

**Comment by TeXitoi** [comment]
You can also join me by email at texitoi AT texitoi DOT eu if needed.

**Pull request merged**
