### PR TITLE
Support `skip = value` syntax

### LINKED ISSUE #256: Custom default value for skipped fields
I propose support for explicit default values for skipped fields:
```rust
#[derive(StructOpt)]
pub struct Opt {
    #[structopt(long, short)]
    number: u32,

    #[structopt(skip = "key")]
    k: String,

    #[structopt(skip = &[1, 2, 3])]
    v: Vec<u32>,
}
```

The syntax is `skip = expr`, the field will be assigned with `(expr).into()` instead of `Default::default()`.

### PR DESCRIPTION
**Pull request by CreepySkeleton**
Closes #256

### CODE REVIEW

**Comment by TeXitoi** [comment]
Approved, but there is conflix

**Comment by CreepySkeleton** [comment]
@TeXitoi rebased

**Comment by TeXitoi** [comment]
Thanks

**Comment by CreepySkeleton** [comment]
@TeXitoi may I ask you to release v0.3.2 with this changes ASAP? Me and some friends of mine could really use this particular feature

**Comment by TeXitoi** [comment]
published

**Pull request merged**
