### PR TITLE
Allow everything that implements ToString as default_value and env

### PR DESCRIPTION
**Pull request by CreepySkeleton**
Implemented handling of `default_value` and `env`. Maybe we could do the other methods too, but we were ever asked only about these two.

### CODE REVIEW

**Comment by TeXitoi** [comment]
Mmm, missunderstanding...

I mean:

```rust
use structopt::StructOpt;

macro_rules! into_str {
    ($x:expr) => {{
        structopt::lazy_static::lazy_static! {
            static ref DATA: String = $x.to_string();
        }
        DATA.as_str()
    }};
}

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(default_value = into_str!(2+5))]
    number: i32,
}
fn main() {
    let cmd = Opt::from_args();
    println!("{:#?}", cmd);
}
```

So no needed modification, usable for all the args, just a helper macro provided by the structopt crate.

**Comment by CreepySkeleton** [comment]
Meh, why not? Already done, doesn't break anything, super easy to use, pretty easy to implement.

**Comment by TeXitoi** [comment]
I can see 2 downside:
 - if it works for `default_value`, the user will not understand why it doesn't work for the other methods that takes `&str`.
 - today, the structopt users can give something to `default_value` that is not a string literal. I can think at least of a static `&str`, and a lazy_static. These examples might not break, but they will allocate one useless time. And maybe it can break in some case, didn't find an example, but I will not be surprised if someone find one.

**Comment by CreepySkeleton** [comment]
Well, it cannot break because everything that people could possibly use here must have been `&str`, because those methods explicitely take `&str`. It has to be `&str` (or another reference that [`impls Deref<str>`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=34b3f704494b9a54dd6b9d2d29ee67724)) in order to compile in the first place. 

We use `.to_string().as_str()` which always return `&str`. Therefore, if it implements `ToString`, it won't break. And `&str` (or something that derefs to it) does implement `ToString`. 

But yeah, the other points stand. I don't really feel like implementing the hack for every single method and I don't like the double allocation either.

So what do we do?

**Comment by CreepySkeleton** [comment]
@TeXitoi do we close it? I'd say yes

**Comment by TeXitoi** [comment]
OK, let's close this. Do you want I do a PR with the macro?

**Pull request closed without merging**
